server:
  port: 8000
  servlet:
    context-path: /miri
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:

  servlet:
    multipart:
      enabled: true
      location: C:\Users\com20\OneDrive\바탕 화면\upload
      # location: C:\\upload
      max-request-size: 30MB
      max-file-size: 10MB


  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miribogi?serverTimezone=Asia/Seoul
    username: fp
    password: 1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#       use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false


      
      
# cos:
#   key: cos1234